oauth2:
  client:
    registration:
      github:
        client-id: "{client-id}"
        client-secret: "{client-secret}"
        response-type: "code"
        scope: "user:email"
        redirect-uri: "http://localhost:8080/login/oauth2/code/github"
      google:
        client-id: "{client-id}"
        client-secret: "{client-secret}"
        response-type: "code"
        scope: "email"
        redirect-uri: "http://localhost:8080/login/oauth2/code/google"
    provider:
      github:
        token-uri: "https://github.com/login/oauth/access_token"
        user-info-uri: "https://api.github.com/user"
        authorization-uri: "https://github.com/login/oauth/authorize"
      google:
        token-uri: "https://oauth2.googleapis.com/token"
        user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
        authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth"



